export const PROMPTS = [
  "What is your favorite color?",
  "What is your go-to girl dinner?",
  "What was your dream job as a kid?",
  "If you could travel anywhere in the world, where would you go?",
  "What would you have as death row meal?",
  "How many pairs of shoes do you own?",
  "What is your favourite romance trope?",
  "What is a hobby you've always wanted to pick up?",
  "What is your favorite movie/series?",
  "What superpower would you want?",
  "What is the first song that comes to your mind right now?",
  "How many basketball players can you name?",
  "What language do you want to learn?",
  "What is the most uncommon food you have ever eaten?",
  "What is the first thing you will do if you won $100M",
  "What is a must play song at a party?",
  "How much money have you spent in the last 7 days?",
  "How many countries have you been to?",
  "What is your favourite vegetable?",
  "How long can you go without leaving the house?",
  "What do you bring to a potluck?",
  "What is your biggest weakness?",
  "Describe the last picture in your camera roll",
  "What are you getting for your first plate at the buffet",
];

//   "Most recently liked Instagram post link",
