export const PROMPTS = [
  "What is your favorite color?",
  "What is your go-to girl dinner?",
  "What was your dream job as a kid?",
  "If you could travel anywhere in the world, where would you go?",
  "What would you have as death row meal?",
  "How many pairs of shoes do you own?",
  "What is your favourite romance trope?",
  "What is your favorite movie/series?",
  "What superpower would you want?",
  "What is the first song that comes to your mind right now?",
  "How many basketball players can you name?",
  "What is the most uncommon food you have ever eaten?",
  "What is the first thing you will do if you won $100M",
  "What is a must play song at a party?",
  "How much money have you spent in the last 7 days?",
  "How many countries have you been to?",
  "What is your favourite vegetable?",
  "How long can you go without leaving the house?",
  "What do you bring to a potluck?",
  "What is your biggest weakness?",
  "Describe the last picture in your camera roll",
  "What are you getting for your first plate at the buffet",
  "When did you go to bed yesterday?",
  "When did you wake up today?",
  "What was your phone's screen time yesterday?",
  "What's the last thing you Googled?",
  "How many instagram notifs do you have right now?",
  "How many alarms do you set in the morning?",
  "How long is your average shower?",
  "How many montly subscriptions do you have?",
  "How long ago was the last time you cried?",
  "What's the last concert you went to?",
  "How many times have you moved in your life?",
  "How many people have you kissed?",
  "How many contacts are in your phone?",
];

//   "Most recently liked Instagram post link",
